-- =============================================================
-- H2 测试专用 Schema（与 init-db.sql 语义等价，兼容 H2 2.x 语法）
-- =============================================================

DROP TABLE IF EXISTS audit_log_items;
DROP TABLE IF EXISTS audit_logs;

-- 主表：纯元数据
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT          PRIMARY KEY,
    timestamp       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trace_id        VARCHAR(64),
    user_id         VARCHAR(128),
    action          VARCHAR(255)    NOT NULL,
    resource_type   VARCHAR(100),
    resource_id     VARCHAR(255),
    business_key    VARCHAR(4096),              -- H2 无 JSONB，用 VARCHAR 代替（MODE=PostgreSQL 下兼容 @> 操作可跳过）
    status          VARCHAR(20)     DEFAULT 'SUCCESS'
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id   ON audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource  ON audit_logs (resource_type, resource_id);

-- 子表：before / after 明细（一对多）
-- H2 2.x 用 BIGINT GENERATED BY DEFAULT AS IDENTITY 替代 BIGSERIAL
CREATE TABLE IF NOT EXISTS audit_log_items (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_log_id    BIGINT          NOT NULL,              -- 关联主表 ID（无外键约束）
    item_index      INT             NOT NULL,
    direction       VARCHAR(10)     NOT NULL,
    item_type       VARCHAR(255),
    payload         CLOB            NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_items_audit_log_id ON audit_log_items (audit_log_id);
CREATE INDEX IF NOT EXISTS idx_items_direction    ON audit_log_items (audit_log_id, direction);
