spring.application.name=audit-log

spring.datasource.url=jdbc:postgresql://postgres:5432/audit_db
spring.datasource.username=audit_user
spring.datasource.password=audit_pass
spring.datasource.driver-class-name=org.postgresql.Driver

minio.endpoint=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=audit-payloads

server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB
server.tomcat.socket-buffer=1048576

server.tomcat.threads.max=400
server.tomcat.threads.min-spare=50

